version: 0.2

env:
  variables:
    IMAGE_NAME: ""
    IMAGE_TAG: ""

phases:
  pre_build:
    commands:
      - echo 'Pre_build_phase'
      - echo 'Installing gh-app-auth CLI...'
      # - pip install uv
      # - uv sync
      - pip install dist/gh_app_auth-0.1.0-py3-none-any.whl
      
      - echo "Saving private key into .pem file..."
      # - echo "$GITHUB_APP_PRIVATE_KEY" > private_key.pem
      - more private_key.pem
      
      - echo "Getting authenticated clone URL..."
      - |
        REPO_URL=$(gh-app-auth configure-git \
          --app-id $GITHUB_APP_ID \
          --installation-id $GITHUB_APP_INSTALL_ID \
          --private-key private_key.pem \
          --repo-owner $GITOPS_REPO_OWNER \
          --repo-name $GITOPS_REPO_NAME)
      
      - echo "Configuring Git..."
      - git config --global user.email "$GIT_MAIL"
      - git config --global user.name "$GIT_USERNAME"

  build:
    commands:
      - echo "Build_phase"
      - echo "Cloning repository..."
      - git clone --depth 1 --branch main "$REPO_URL"
      - cd $GITOPS_REPO_NAME
      - ls -halt
      - pip install -r requirements.txt
      - echo "Executing <python image_tag_updater.py -i $IMAGE_NAME -t $IMAGE_TAG -c image_tag_mappings.json>"
      - python image_tag_updater.py -i $IMAGE_NAME -t $IMAGE_TAG -c image_tag_mappings.json
      - git add *
      - git commit -m "Automatic Pipeline - Updated image $IMAGE_NAME to version $IMAGE_TAG"
      - git push

  post_build:
    commands:
      - echo 'Post_build_phase'
